/**
 * Generated by `npm run tools:index`. Do not edit by hand.
 *
 * One import per tool, in file-name order. The catalogue's display order is
 * decided by the registry, not by this list.
 */
import type { ToolDefinition } from '../types';
import { tool as hourlyToSalary } from './hourly-to-salary';
import { tool as salaryAfterTax } from './salary-after-tax';
import { tool as paycheck } from './paycheck';
import { tool as bonusTax } from './bonus-tax';
import { tool as mortgagePayment } from './mortgage-payment';
import { tool as loan } from './loan';
import { tool as compoundInterest } from './compound-interest';
import { tool as debtPayoff } from './debt-payoff';
import { tool as inflation } from './inflation';
import { tool as homeAffordability } from './home-affordability';
import { tool as insuranceCost } from './insurance-cost';
import { tool as healthInsurance } from './health-insurance';
import { tool as marketplacePlans } from './marketplace-plans';
import { tool as medicareCost } from './medicare-cost';
import { tool as costOfLiving } from './cost-of-living';
import { tool as electricityCost } from './electricity-cost';
import { tool as applianceElectricity } from './appliance-electricity';
import { tool as concrete } from './concrete';
import { tool as evVsGas } from './ev-vs-gas';
import { tool as roadTripFuel } from './road-trip-fuel';
import { tool as carAffordability } from './car-affordability';
import { tool as autoCoverage } from './auto-coverage';
import { tool as perDiem } from './per-diem';
import { tool as businessDays } from './business-days';
import { tool as unitPrice } from './unit-price';
import { tool as whereCheaper } from './where-cheaper';
import { tool as recipeScaler } from './recipe-scaler';
import { tool as bmi } from './bmi';
import { tool as calorie } from './calorie';
import { tool as tdee } from './tdee';
import { tool as bmr } from './bmr';
import { tool as bodyFat } from './body-fat';
import { tool as tip } from './tip';
import { tool as age } from './age';
import { tool as time } from './time';
import { tool as randomNumber } from './random-number';
import { tool as timeCard } from './time-card';
import { tool as date } from './date';
import { tool as daysFromToday } from './days-from-today';
import { tool as percentage } from './percentage';
import { tool as percentChange } from './percent-change';
import { tool as scientific } from './scientific';
import { tool as fraction } from './fraction';
import { tool as unitConversion } from './unit-conversion';
import { tool as grade } from './grade';
import { tool as gpa } from './gpa';
import { tool as squareFootage } from './square-footage';
import { tool as carLoan } from './car-loan';
import { tool as investment } from './investment';
import { tool as retirement } from './retirement';
import { tool as amortization } from './amortization';
import { tool as cd } from './cd';
import { tool as interest } from './interest';
import { tool as rothIra } from './roth-ira';
import { tool as tool401k } from './401k';
import { tool as refinance } from './refinance';
import { tool as mortgagePayoff } from './mortgage-payoff';
import { tool as creditCardPayoff } from './credit-card-payoff';
import { tool as effectiveTaxRate } from './effective-tax-rate';

export const registryTools: ToolDefinition[] = [
  hourlyToSalary,
  salaryAfterTax,
  paycheck,
  bonusTax,
  mortgagePayment,
  loan,
  compoundInterest,
  debtPayoff,
  inflation,
  homeAffordability,
  insuranceCost,
  healthInsurance,
  marketplacePlans,
  medicareCost,
  costOfLiving,
  electricityCost,
  applianceElectricity,
  concrete,
  evVsGas,
  roadTripFuel,
  carAffordability,
  autoCoverage,
  perDiem,
  businessDays,
  unitPrice,
  whereCheaper,
  recipeScaler,
  bmi,
  calorie,
  tdee,
  bmr,
  bodyFat,
  tip,
  age,
  time,
  randomNumber,
  timeCard,
  date,
  daysFromToday,
  percentage,
  percentChange,
  scientific,
  fraction,
  unitConversion,
  grade,
  gpa,
  squareFootage,
  carLoan,
  investment,
  retirement,
  amortization,
  cd,
  interest,
  rothIra,
  tool401k,
  refinance,
  mortgagePayoff,
  creditCardPayoff,
  effectiveTaxRate,
];
