/**
 * Generated by scripts/ingest-gsa-perdiem.ts from data/gsa-perdiem/snapshots.
 * The Worker can only see JSON the bundler is given as a literal import.
 * Do not import current.json here or the tables ship twice.
 */
import type { GsaPerDiemSnapshot } from './gsa-perdiem';
import gsaPerdiemConusFy2026V1 from '@/data/gsa-perdiem/snapshots/gsa-perdiem-conus-fy2026-v1.json';

export const gsaPerDiemSnapshotDocuments = [
  gsaPerdiemConusFy2026V1,
] as unknown as GsaPerDiemSnapshot[];
