export const CALCULATOR_ES: Record<string, string> = {
 'Before taxes and deductions': 'Antes de impuestos y deducciones', 'Annual ÷ 12': 'Anual ÷ 12', 'Annual ÷ 24': 'Anual ÷ 24', 'Annual ÷ 26': 'Anual ÷ 26', 'Annual ÷ 52': 'Anual ÷ 52',

 'How we got this': 'Cómo lo calculamos', 'What we assumed': 'Supuestos del cálculo', 'Technical details': 'Detalles técnicos', 'Report incorrect result': 'Informar de un resultado incorrecto', 'Result copied': 'Resultado copiado', 'Copied the working': 'Cálculo copiado', 'Copy result and working': 'Copiar resultado y pasos', 'Before tax': 'Antes de impuestos', 'Monthly gross': 'Bruto mensual', 'Weekly gross': 'Bruto semanal', 'Daily gross': 'Bruto diario', 'Twice a month': 'Dos veces al mes', 'Every two weeks': 'Cada dos semanas',

 'Your numbers':'Tus datos','Result':'Resultado','Results':'Resultados','Reset':'Restablecer','Calculate':'Calcular','Copy':'Copiar','Copied':'Copiado','Copy result':'Copiar resultado','Copied!':'¡Copiado!','Show the steps':'Ver los pasos','Assumptions':'Supuestos','How we calculated this':'Cómo lo calculamos','Breakdown':'Desglose','Details':'Detalles','Compare':'Comparar','Save scenario':'Guardar escenario','Clear':'Borrar','Remove':'Eliminar','Add':'Añadir','Monthly':'Mensual','Yearly':'Anual','Weekly':'Semanal','Annually':'Anualmente','Daily':'Diario','Biweekly':'Cada dos semanas','Semimonthly':'Dos veces al mes','Single':'Soltero','Married filing jointly':'Casados, declaración conjunta','Married filing separately':'Casados, declaración separada','Head of household':'Cabeza de familia',
 'Amount':'Importe','Balance':'Saldo','Current balance':'Saldo actual','Principal':'Capital','Starting amount':'Importe inicial','Value':'Valor','Original value':'Valor original','New value':'Valor nuevo','Rate':'Tasa','Interest rate':'Tasa de interés','Annual interest rate':'Tasa de interés anual','Annual percentage yield':'Rendimiento porcentual anual','Assumed annual return':'Rendimiento anual supuesto','Nominal annual rate':'Tasa anual nominal','Term':'Plazo','Years':'Años','years':'años','months':'meses','days':'días','hours':'horas','weeks':'semanas','miles':'millas','servings':'raciones','years old':'años de edad','/ hour':'/ hora','/ month':'/ mes','/ year':'/ año','% / year':'% / año','% of salary':'% del salario','× base':'× base','/ gal':'/ galón',
 'Loan amount':'Importe del préstamo','Loan term':'Plazo del préstamo','Loan term unit':'Unidad del plazo','Monthly payment':'Pago mensual','Monthly loan payment':'Cuota mensual del préstamo','Additional monthly payment':'Pago mensual adicional','Extra monthly principal':'Capital adicional mensual','Down payment':'Pago inicial','Home price':'Precio de la vivienda','Monthly HOA':'Cuota mensual de la comunidad','Yearly property tax':'Impuesto anual sobre la propiedad','Yearly home insurance':'Seguro anual de la vivienda','Closing costs':'Gastos de cierre','Current principal':'Capital pendiente','Original term':'Plazo original','Remaining term':'Plazo restante','New term':'Nuevo plazo','New interest rate':'Nueva tasa de interés','Next payment date':'Fecha del próximo pago','First payment date':'Fecha del primer pago','Payments already made':'Pagos ya realizados','Amount financed':'Importe financiado','Monthly mortgage payment':'Cuota mensual de la hipoteca','Comfortable home price':'Precio de vivienda dentro del presupuesto',

 'Hourly rate':'Paga por hora','Hourly wage to annual salary':'De paga por hora a salario anual','Put in your rate, hours, and how many weeks you get paid. This is before taxes.':'Introduce la paga por hora, las horas trabajadas y las semanas pagadas. El resultado es antes de impuestos.','Regular hours':'Horas ordinarias','Hours per week at your base rate':'Horas semanales a la tarifa base','Overtime hours':'Horas extra','Only hours paid at the overtime rate':'Solo las horas pagadas como horas extra','Overtime rate':'Multiplicador de horas extra','Paid weeks':'Semanas pagadas','Use 52 if you are paid every week of the year':'Usa 52 si recibes paga todas las semanas del año','Estimated annual gross pay':'Sueldo bruto anual estimado','Annual gross salary':'Sueldo bruto anual','Gross income':'Ingreso bruto','Income':'Ingresos','Salary':'Salario','Pay frequency':'Frecuencia de pago','Filing status':'Estado civil tributario','State':'Estado','Your state':'Tu estado','Residential state':'Estado de residencia','Tax year':'Año fiscal','Dependents':'Dependientes','Children':'Hijos','Adults':'Adultos','Other dependents':'Otros dependientes','Qualifying children':'Hijos que cumplen los requisitos','Qualifying children under 17':'Hijos menores de 17 años que cumplen los requisitos','Adjusted gross income':'Ingreso bruto ajustado','Modified AGI':'Ingreso bruto ajustado modificado','Earned income':'Ingreso del trabajo','Investment income':'Ingresos por inversiones','Other taxable income':'Otros ingresos sujetos a impuestos','Federal income tax withheld':'Impuesto federal retenido','Estimated net paycheck':'Nómina neta estimada','Estimated take-home pay':'Ingreso neto estimado','Monthly take-home pay':'Sueldo neto mensual','Monthly take-home':'Ingreso neto mensual','Before anything is taken out':'Antes de cualquier deducción','After taxes. Not gross salary.':'Después de impuestos. No es el sueldo bruto.','After taxes and deductions. Not gross salary.':'Después de impuestos y deducciones. No es el sueldo bruto.','Monthly debts':'Deudas mensuales','Other monthly expenses':'Otros gastos mensuales','Other essentials':'Otros gastos básicos','Monthly housing cost':'Gasto mensual de vivienda','Housing':'Vivienda','Transportation':'Transporte','Food':'Alimentación',

 'Monthly contribution':'Aportación mensual','Recurring contribution':'Aportación periódica','Contribution frequency':'Frecuencia de aportación','Contribution timing':'Momento de la aportación','Compounding':'Capitalización','Current savings':'Ahorros actuales','Current age':'Edad actual','Retirement age':'Edad de jubilación','Salary growth':'Crecimiento salarial','Employee contribution':'Aportación del trabajador','Employer match rate':'Aportación equivalente del empleador','Percent of salary':'Porcentaje del sueldo','Match applies up to':'Límite de la aportación equivalente','Projected balance':'Saldo proyectado','Estimated ending balance':'Saldo final estimado','Estimated ending value':'Valor final estimado','Ending balance':'Saldo final','An assumption, not a forecast':'Un supuesto, no un pronóstico','Count':'Cantidad','Minimum':'Mínimo','Maximum':'Máximo','Quantity':'Cantidad','Total':'Total',

 'Length':'Largo','Width':'Ancho','Height':'Altura','Weight':'Peso','Thickness':'Espesor','Length unit':'Unidad de longitud','Unit':'Unidad','Units':'Unidades','Unit system':'Sistema de unidades','Calculation mode':'Modo de cálculo','Calculator mode':'Modo de calculadora','Mode':'Modo','Waste allowance':'Margen de desperdicio','Bag size':'Tamaño de la bolsa','Price per bag (optional)':'Precio por bolsa (opcional)','Total area':'Superficie total','Spaces':'Espacios','Total hours':'Horas totales','Powertrain':'Motorización','Vehicle price':'Precio del vehículo','Vehicle efficiency':'Eficiencia del vehículo','Miles per gallon':'Millas por galón','Fuel economy':'Consumo de combustible','Gas price':'Precio de la gasolina','Trip distance':'Distancia del viaje','Annual miles':'Millas anuales','Miles driven per year':'Millas conducidas al año','Monthly gasoline':'Gasto mensual en gasolina','Monthly electricity':'Gasto mensual en electricidad','Insurance':'Seguro','Maintenance and repairs':'Mantenimiento y reparaciones','Sales tax and fees':'Impuestos de venta y cargos','Trade-in':'Vehículo entregado a cambio','Trade-in value':'Valor del vehículo entregado','Charging loss':'Pérdida de carga','Charging losses':'Pérdidas de carga','Battery energy per 100 miles':'Energía de batería por cada 100 millas','EV efficiency':'Eficiencia del auto eléctrico',

 'Wattage':'Potencia en vatios','Hours used per day':'Horas de uso al día','Days used per week':'Días de uso por semana','Running share of those hours':'Proporción de esas horas en funcionamiento','Monthly usage':'Consumo mensual','Your own electricity rate':'Tu tarifa eléctrica','Your electricity rate (optional)':'Tu tarifa eléctrica (opcional)','Estimated monthly electric bill':'Factura eléctrica mensual estimada','Estimated monthly electricity cost':'Costo eléctrico mensual estimado','Estimated fuel cost':'Costo estimado de combustible','Estimated monthly loan payment':'Cuota mensual estimada del préstamo','Estimated monthly payment':'Pago mensual estimado','Estimated maximum vehicle price':'Precio máximo estimado del vehículo','State electricity average':'Promedio de electricidad del estado',

 'Birth date':'Fecha de nacimiento','Birth year':'Año de nacimiento','Start date':'Fecha inicial','Starting date':'Fecha inicial','End date':'Fecha final','As of':'A fecha de','Starting year':'Año inicial','Ending year':'Año final','Starting month':'Mes inicial','Ending month':'Mes final','Target date':'Fecha objetivo','Days between':'Días entre fechas','Calendar days':'Días naturales','Business days':'Días laborables','Business days to add':'Días laborables que añadir','Workdays':'Días laborables','Days from today':'Días desde hoy','Direction':'Dirección','Operation':'Operación','From':'De','To':'A','First hours':'Primer valor: horas','First minutes':'Primer valor: minutos','First seconds':'Primer valor: segundos','Second hours':'Segundo valor: horas','Second minutes':'Segundo valor: minutos','Second seconds':'Segundo valor: segundos','Completed age':'Edad cumplida','Resulting date':'Fecha resultante','Resulting calendar date':'Fecha resultante',

 'Bill subtotal':'Subtotal de la cuenta','Tip':'Propina','Tax':'Impuesto','People':'Personas','Package price':'Precio del paquete','Original servings':'Raciones originales','Desired servings':'Raciones deseadas','Recipe ingredients':'Ingredientes','Scale factor':'Factor de escala','Scale the recipe':'Ajustar la receta','Label':'Nombre','Age':'Edad','Your age':'Tu edad','Activity':'Actividad','Sex used by the equation':'Sexo utilizado en la fórmula','Waist':'Cintura','Neck':'Cuello','Hip':'Cadera','Estimated BMI':'IMC estimado','Estimated BMR':'Metabolismo basal estimado','Estimated TDEE':'Gasto energético diario estimado','Estimated body-fat percentage':'Porcentaje estimado de grasa corporal','Estimated daily calories':'Calorías diarias estimadas','Calorie goal':'Objetivo de calorías','Modeled goal':'Objetivo del modelo','Adult estimate, 18–80':'Estimación para adultos de 18 a 80 años','Courses':'Asignaturas','Grade items':'Elementos de evaluación','Calculated grade':'Nota calculada','Weighted grade':'Nota ponderada','Exact result':'Resultado exacto','Converted value':'Valor convertido','Generated numbers':'Números generados','Equation':'Ecuación','Expression':'Expresión','Angle mode':'Unidad angular','Percentage':'Porcentaje','Percentage operation':'Operación porcentual','Percent change':'Cambio porcentual','Left numerator':'Numerador izquierdo','Left denominator':'Denominador izquierdo','Right numerator':'Numerador derecho','Right denominator':'Denominador derecho','Integer mode':'Modo de enteros','Uniqueness':'Sin repetición','Optional':'Opcional',

 'Location':'Ubicación','Destination':'Destino','County':'Condado','ZIP code':'Código postal','Leaving':'Salida','Returning':'Regreso','Bedrooms':'Dormitorios','Compare with':'Comparar con','Balance left':'Saldo pendiente','Shifts':'Turnos','Hours worked':'Horas trabajadas','Hours per week':'Horas por semana',

 'Figure':'Concepto','Difference':'Diferencia','Solve':'Calcular','Enter a target first.':'Introduce primero un objetivo.','High confidence':'Confianza alta','Medium confidence':'Confianza media','Low confidence':'Confianza básica',
 'Filing status, dependents and tax year':'Estado civil tributario, dependientes y año fiscal',
 'Defaults cover the common case: single, no dependents, the current year.':'Los valores predeterminados cubren el caso habitual: soltero, sin dependientes, año actual.',
 'Taxes, insurance and HOA':'Impuestos, seguro y gastos de comunidad',
 'Medicare wages for Additional Medicare Tax':'Salarios sujetos a Medicare para el impuesto adicional',
 'Use your own premiums':'Introduce tus propias primas',
 'Have a quote or renewal?':'¿Tienes un presupuesto o una renovación?',
 'Self-employment, dependents, estimated payments':'Trabajo por cuenta propia, dependientes y pagos estimados',
 'ZIP code and largest conforming price':'Código postal y precio máximo conforme',
 'A ZIP is mapped to a county. Down payment is only used to show the largest conforming purchase price.':'El código postal se asocia al condado. El pago inicial solo se usa para calcular el precio máximo de compra conforme.',
 'MAGI and net investment income for NIIT':'MAGI e ingresos netos por inversiones para el NIIT',
 'Check whether this plan is an HDHP':'Comprobar si el plan califica como HDHP',
 'Optional. The IRS test is on deductible and out-of-pocket maximum, not on the metal tier.':'Opcional. El criterio del IRS evalúa el deducible y el desembolso máximo, no la categoría de metal.',
 'Exemption and a prior VA loan':'Exención y préstamo VA anterior',
 'Disability compensation, DIC, or a Purple Heart can zero the fee. VA still has to agree.':'Una compensación por discapacidad, DIC o Corazón Púrpura puede anular la comisión. El Departamento de VA debe confirmarlo.',
 'Gross pay this period':'Sueldo bruto de este periodo',
};
