/**
 * Rebuild `lib/tools/registry/index.ts` from the fragments on disk.
 *
 * The index is generated rather than hand-maintained because the point of the
 * split is that adding a tool touches one new file. If the index were edited by
 * hand, two people adding tools at once would still collide in it — just in a
 * shorter file than before. Generated, a collision is resolved by running this
 * again rather than by reading a diff.
 *
 * Explicit imports rather than a bundler glob: this list is consumed by the
 * RSC build, the Worker build and vitest, and an explicit list behaves the same
 * in all three.
 */
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const REGISTRY_DIR = path.join(process.cwd(), 'lib', 'tools', 'registry');

/**
 * A fragment's variable name: `hourly-to-salary` becomes `hourlyToSalary`.
 *
 * Ids may start with a digit — `401k` is a tool — and an identifier may not, so
 * those get a `tool` prefix rather than producing a file that will not parse.
 */
export function importAlias(toolId: string): string {
  const camel = toolId.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase());
  return /^[A-Za-z_$]/.test(camel) ? camel : `tool${camel[0].toUpperCase()}${camel.slice(1)}`;
}

/**
 * Fragment ids in the order the index should list them.
 *
 * Registry order is editorial, not alphabetical: `getToolsByCategory` hands it
 * straight to the category hub pages, so it is what a reader sees. Sorting the
 * fragments would silently reshuffle every hub, so the existing order is kept
 * and genuinely new tools are appended for someone to place deliberately.
 */
export async function registryFragmentIds(): Promise<string[]> {
  const files = await readdir(REGISTRY_DIR);
  const present = new Set(
    files.filter((file) => file.endsWith('.ts') && file !== 'index.ts').map((file) => file.slice(0, -3)),
  );

  let existingOrder: string[] = [];
  try {
    const current = await readFile(path.join(REGISTRY_DIR, 'index.ts'), 'utf8');
    existingOrder = [...current.matchAll(/from '\.\/([^']+)'/g)].map((match) => match[1]);
  } catch {
    // No index yet. Everything is new, and alphabetical is as good a first
    // guess as any — someone orders it once, and it is kept from then on.
  }

  const kept = existingOrder.filter((id) => present.has(id));
  const added = [...present].filter((id) => !kept.includes(id)).sort();
  return [...kept, ...added];
}

export function renderIndex(ids: readonly string[]): string {
  const imports = ids.map((id) => `import { tool as ${importAlias(id)} } from './${id}';`).join('\n');
  const entries = ids.map((id) => `  ${importAlias(id)},`).join('\n');
  return `/**
 * Generated by \`npm run tools:index\`. Do not edit by hand.
 *
 * One import per tool, in file-name order. The catalogue's display order is
 * decided by the registry, not by this list.
 */
import type { ToolDefinition } from '../types';
${imports}

export const registryTools: ToolDefinition[] = [
${entries}
];
`;
}

async function main(): Promise<void> {
  const ids = await registryFragmentIds();
  await writeFile(path.join(REGISTRY_DIR, 'index.ts'), renderIndex(ids), 'utf8');
  console.log(`Wrote lib/tools/registry/index.ts with ${ids.length} tools.`);
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  await main();
}
