/**
 * Rebuild `lib/tools/registry/index.ts` from the fragments on disk.
 *
 * The index is generated rather than hand-maintained because the point of the
 * split is that adding a tool touches one new file. If the index were edited by
 * hand, two people adding tools at once would still collide in it — just in a
 * shorter file than before. Generated, a collision is resolved by running this
 * again rather than by reading a diff.
 *
 * Explicit imports rather than a bundler glob: this list is consumed by the
 * RSC build, the Worker build and vitest, and an explicit list behaves the same
 * in all three.
 */
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const REGISTRY_DIR = path.join(process.cwd(), 'lib', 'tools', 'registry');

/**
 * A fragment's variable name: `hourly-to-salary` becomes `hourlyToSalary`.
 *
 * Ids may start with a digit — `401k` is a tool — and an identifier may not, so
 * those get a `tool` prefix rather than producing a file that will not parse.
 */
export function importAlias(toolId: string): string {
  const camel = toolId.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase());
  return /^[A-Za-z_$]/.test(camel) ? camel : `tool${camel[0].toUpperCase()}${camel.slice(1)}`;
}

/**
 * Fragment ids in the order the index should list them.
 *
 * Registry order is editorial, not alphabetical: `getToolsByCategory` hands it
 * straight to the category hub pages, so it is what a reader sees. Sorting the
 * fragments would silently reshuffle every hub, so the existing order is kept
 * and genuinely new tools are appended for someone to place deliberately.
 */
export async function registryFragmentIds(): Promise<string[]> {
  const files = await readdir(REGISTRY_DIR);
  const present = new Set(
    files.filter((file) => file.endsWith('.ts') && file !== 'index.ts').map((file) => file.slice(0, -3)),
  );

  let existingOrder: string[] = [];
  try {
    const current = await readFile(path.join(REGISTRY_DIR, 'index.ts'), 'utf8');
    existingOrder = [...current.matchAll(/from '\.\/([^']+)'/g)].map((match) => match[1]);
  } catch {
    // No index yet. Everything is new, and alphabetical is as good a first
    // guess as any — someone orders it once, and it is kept from then on.
  }

  const kept = existingOrder.filter((id) => present.has(id));
  const added = [...present].filter((id) => !kept.includes(id)).sort();
  return [...kept, ...added];
}

export function renderIndex(ids: readonly string[]): string {
  const imports = ids.map((id) => `import { tool as ${importAlias(id)} } from './${id}';`).join('\n');
  const entries = ids.map((id) => `  ${importAlias(id)},`).join('\n');
  return `/**
 * Generated by \`npm run tools:index\`. Do not edit by hand.
 *
 * One import per tool, in file-name order. The catalogue's display order is
 * decided by the registry, not by this list.
 */
import type { ToolDefinition } from '../types';
${imports}

export const registryTools: ToolDefinition[] = [
${entries}
];
`;
}

/**
 * What can go wrong now that merge conflicts cannot.
 *
 * Splitting the registry traded one failure mode for others: a fragment that
 * declares a second tool's id, two fragments claiming the same URL, a file that
 * forgot to export `tool`, or an index nobody regenerated. Every one of those
 * is silent — the build succeeds and the catalogue is quietly wrong — so they
 * are checked here and in `tests/tool-registry-split.spec.ts` rather than left
 * to be noticed on a live page.
 */
export type FragmentProblem = { readonly file: string; readonly problem: string };

export async function fragmentProblems(): Promise<FragmentProblem[]> {
  const ids = await registryFragmentIds();
  const problems: FragmentProblem[] = [];
  const declaredIds = new Map<string, string>();
  const declaredPaths = new Map<string, string>();

  for (const id of ids) {
    const file = `${id}.ts`;
    const source = await readFile(path.join(REGISTRY_DIR, file), 'utf8');

    const exports = [...source.matchAll(/export const (\w+)\s*:/g)].map((match) => match[1]);
    if (!exports.includes('tool')) problems.push({ file, problem: 'does not export `tool`' });
    if (exports.length > 1) problems.push({ file, problem: `exports more than the tool: ${exports.join(', ')}` });

    const declaredId = /\bid:\s*'([^']+)'/.exec(source)?.[1];
    if (!declaredId) problems.push({ file, problem: 'declares no id' });
    else if (declaredId !== id) problems.push({ file, problem: `declares id '${declaredId}', so the file name lies` });
    else {
      const clash = declaredIds.get(declaredId);
      if (clash) problems.push({ file, problem: `declares the same id as ${clash}` });
      declaredIds.set(declaredId, file);
    }

    const declaredPath = /\bpath:\s*'([^']+)'/.exec(source)?.[1];
    if (!declaredPath) problems.push({ file, problem: 'declares no path' });
    else {
      const clash = declaredPaths.get(declaredPath);
      if (clash) problems.push({ file, problem: `claims ${declaredPath}, already claimed by ${clash}` });
      declaredPaths.set(declaredPath, file);
    }
  }
  return problems;
}

async function main(): Promise<void> {
  const problems = await fragmentProblems();
  if (problems.length > 0) {
    for (const { file, problem } of problems) console.error(`  ${file}: ${problem}`);
    throw new Error(`${problems.length} registry fragment problem(s). The index was not written.`);
  }

  const ids = await registryFragmentIds();
  await writeFile(path.join(REGISTRY_DIR, 'index.ts'), renderIndex(ids), 'utf8');
  console.log(`Wrote lib/tools/registry/index.ts with ${ids.length} tools.`);
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  await main();
}
