import path from 'node:path';
import { readdir } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import {
  GSA_MIE_BREAKDOWN_URL,
  GSA_PERDIEM_API_URL,
  gsaFiscalYearsToDiscover,
  gsaPerDiemSnapshotSchema,
  markLatestPublishedPerDiemReleases,
  normalizeGsaPerDiemResponse,
  parseMieBreakdowns,
  type GsaPerDiemSnapshot,
  type PerDiemRelease,
} from '../lib/data/gsa-perdiem';
import {
  acquireIngestionLock,
  atomicWrite,
  evaluateRefreshDecision,
  fetchText,
  promoteSnapshotFiles,
  readJsonIfPresent,
  sealNormalizedSnapshot,
  sha256,
  syncPromotionPointer,
} from './ingest-io';

const root = process.cwd();
const dataDirectory = path.join(root, 'data', 'gsa-perdiem');
const catalogPath = path.join(root, 'lib', 'data', 'gsa-perdiem-catalog.ts');

function catalogIdentifier(fileName: string): string {
  const stem = fileName.replace(/\.json$/, '');
  const camel = stem.replace(/[^a-zA-Z0-9]+(.)/g, (_, character: string) => character.toUpperCase()).replace(/[^a-zA-Z0-9]/g, '');
  return camel.replace(/^(.)/, (character) => character.toLowerCase());
}

async function writeSnapshotCatalog(): Promise<void> {
  const snapshotDirectory = path.join(dataDirectory, 'snapshots');
  const files = (await readdir(snapshotDirectory)).filter((name) => name.endsWith('.json')).sort();
  if (files.length === 0) throw new Error('GSA per diem snapshots directory is empty; cannot generate the catalog.');
  const imports = files.map((file) => `import ${catalogIdentifier(file)} from '@/data/gsa-perdiem/snapshots/${file}';`).join('\n');
  const list = files.map((file) => `  ${catalogIdentifier(file)},`).join('\n');
  const source = `/**
 * Generated by scripts/ingest-gsa-perdiem.ts from data/gsa-perdiem/snapshots.
 * The Worker can only see JSON the bundler is given as a literal import.
 * Do not import current.json here or the tables ship twice.
 */
import type { GsaPerDiemSnapshot } from './gsa-perdiem';
${imports}

export const gsaPerDiemSnapshotDocuments = [
${list}
] as unknown as GsaPerDiemSnapshot[];
`;
  await atomicWrite(catalogPath, source);
}

async function upsertPerDiemRelease(snapshot: GsaPerDiemSnapshot): Promise<void> {
  const releasesPath = path.join(dataDirectory, 'releases.json');
  const catalog = await readJsonIfPresent<{ schemaVersion: string; releases: PerDiemRelease[] }>(releasesPath)
    ?? { schemaVersion: '1.0.0', releases: [] };
  const next: PerDiemRelease = {
    snapshotId: snapshot.snapshotId,
    fiscalYear: snapshot.fiscalYear,
    announcementPublishedAt: snapshot.publishedAt,
    datasetPublishedAt: snapshot.fetchedAt,
    effectiveFrom: snapshot.effectiveFrom,
    effectiveTo: snapshot.effectiveTo,
    latestPublished: true,
  };
  const releases = markLatestPublishedPerDiemReleases(
    [
      ...catalog.releases.filter((release) => release.snapshotId !== next.snapshotId),
      next,
    ].sort((left, right) => left.fiscalYear - right.fiscalYear),
  );
  await atomicWrite(releasesPath, `${JSON.stringify({ schemaVersion: '1.0.0', releases }, null, 2)}\n`);
}

function fiscalYearsToFetch(): number[] {
  const explicit = process.env.GSA_FISCAL_YEAR;
  if (explicit) {
    const year = Number(explicit);
    if (!Number.isInteger(year) || year < 2000) {
      throw new Error(`GSA_FISCAL_YEAR must be a fiscal year, got ${explicit}.`);
    }
    return [year];
  }
  return gsaFiscalYearsToDiscover();
}

async function fetchYearPayload(fiscalYear: number, apiKey: string): Promise<unknown | undefined> {
  const ratesUrl = `${GSA_PERDIEM_API_URL}/${fiscalYear}?api_key=${apiKey}`;
  try {
    const ratesText = await fetchText(ratesUrl, { headers: { accept: 'application/json' } });
    const payload = JSON.parse(ratesText) as unknown;
    if (!Array.isArray(payload) || payload.length === 0) {
      console.log(`GSA FY${fiscalYear} response is empty; treating as unpublished.`);
      return undefined;
    }
    return payload;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (/\bHTTP 404\b/.test(message)) {
      console.log(`GSA has not published FY${fiscalYear} yet.`);
      return undefined;
    }
    throw error;
  }
}

async function ingestYear(
  fiscalYear: number,
  payload: unknown,
  mieBreakdowns: ReturnType<typeof parseMieBreakdowns>,
): Promise<void> {
  const fetchedAt = new Date().toISOString();
  const rawText = `${JSON.stringify([
    { source: `${GSA_PERDIEM_API_URL}/${fiscalYear}`, payload },
    { source: GSA_MIE_BREAKDOWN_URL, mieBreakdowns },
  ], null, 2)}\n`;

  const normalized = sealNormalizedSnapshot(
    normalizeGsaPerDiemResponse(payload, mieBreakdowns, { fiscalYear, fetchedAt, rawSha256: sha256(rawText) }),
  );
  gsaPerDiemSnapshotSchema.parse(normalized);

  const yearSnapshotPath = path.join(dataDirectory, 'snapshots', `${normalized.snapshotId}.json`);
  const previousYear = await readJsonIfPresent<GsaPerDiemSnapshot>(yearSnapshotPath);
  const decision = evaluateRefreshDecision({
    previous: previousYear,
    nextPeriod: normalized.observationPeriod,
    payloadUnchanged: previousYear
      ? JSON.stringify(normalized.destinations) === JSON.stringify(previousYear.destinations)
      : true,
  });

  if (decision === 'already-current') {
    await upsertPerDiemRelease(previousYear ?? normalized);
    if (previousYear && await syncPromotionPointer(dataDirectory, previousYear)) {
      console.log(`Repaired the promotion pointer for ${previousYear.snapshotId}.`);
    } else {
      console.log(`${normalized.snapshotId} is already current; no rate files changed.`);
    }
    return;
  }

  // current.json tracks the latest published year, like HUD, even when that
  // year is not effective yet. Effective-vs-published lives in releases.json.
  await promoteSnapshotFiles({
    dataDirectory,
    snapshot: normalized,
    normalizedFileName: 'perdiem.normalized.json',
    rawRelativePath: path.join('raw', `fy${fiscalYear}.json`),
    rawContents: rawText,
  });
  await upsertPerDiemRelease(normalized);

  console.log(
    `Published ${normalized.snapshotId}: ${normalized.destinations.length} CONUS destinations, ${normalized.mieBreakdowns.length} M&IE tiers.`,
  );
}

async function runIngestion(): Promise<void> {
  // DEMO_KEY works for this volume; set GSA_API_KEY for a signed, higher quota.
  const apiKey = process.env.GSA_API_KEY ?? 'DEMO_KEY';
  const mieHtml = await fetchText(GSA_MIE_BREAKDOWN_URL, { headers: { accept: 'text/html' } });
  const mieBreakdowns = parseMieBreakdowns(mieHtml);

  let ingested = 0;
  for (const fiscalYear of fiscalYearsToFetch()) {
    const payload = await fetchYearPayload(fiscalYear, apiKey);
    if (!payload) continue;
    await ingestYear(fiscalYear, payload, mieBreakdowns);
    ingested += 1;
    break;
  }
  if (ingested === 0) {
    throw new Error('GSA published no fetchable CONUS fiscal year.');
  }
  await writeSnapshotCatalog();
}

if (import.meta.url === pathToFileURL(path.resolve(process.argv[1] ?? '')).href) {
  const releaseLock = await acquireIngestionLock(dataDirectory);
  try {
    await runIngestion();
  } finally {
    await releaseLock();
  }
}
